import React, { useEffect, useRef, useState } from 'react';
import '../../CSS/Perplexity.css';
import { yupResolver } from "@hookform/resolvers/yup";
import * as yup from "yup";
import emailjs from "emailjs-com";
import { useForm } from "react-hook-form";
import { useNavigate } from "react-router-dom";
import clock from "../../images/perplexity-page/clock-image.png";
import Insightdata from "../../Data/Resources-Data/Insightdata.js";
import linkedin from "../../images/perplexity-page/linkedin.svg";
import facebook from "../../images/perplexity-page/facebook.svg";
import twitter from "../../images/perplexity-page/twitter.svg";
import instagram from "../../images/perplexity-page/instagram.svg";
import { Helmet } from "react-helmet";

const schema = yup
    .object()
    .shape({
        fName: yup
            .string()
            .matches(/^[a-zA-Z ]*$/, "First Name is not valid")
            .required("First Name is required"),
        lName: yup
            .string()
            .matches(/^[a-zA-Z ]*$/, "Last Name is not valid")
            .required("Last Name is required"),
        email: yup
            .string()
            .email()
            .matches(
                /^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/,
                "email is required"
            )
            .required("email is required"),
        // phoneNumber: yup.string().when("$exist", {
        //   is: (exist) => exist,
        //   then: yup
        //     .string()
        //     .matches(
        //       /^[\+]?[(]?[0-9]{3}[)]?[-\s\.]?[0-9]{3}[-\s\.]?[0-9]{4,6}$/,
        //       "phonenumber is not valid"
        //     ),
        //   otherwise: yup.string(),
        // }),
        // acceptCheckbox: yup.bool().oneOf([true], "Checkbox selection is required"),
        cName: yup
            .string()
            .matches(/^[a-zA-Z ]*$/, "Company Name is not valid")
            .required("Company is required"),
    })
    .required();

const headings = [
    {
        "id": "heading1",
        title:"What is AIOps and explore how it is revolutionizing the retail industry by solving complex challenges?",
       heading1:"What is AIOps?",
       description2:"Artificial Intelligence for IT Operations (AIOps) is a discipline that combines the power of Artificial Intelligence (AI), Natural Language Processing (NLP), and Machine Learning (ML) to automate traditional IT operations (such as event correlation, anomaly detection, and causality determination). It is designed to help organizations better manage their IT infrastructure, reduce downtime, and optimize system performance. AIOps provides IT teams with a unified view of their entire IT environment and automates many of the routine tasks associated with monitoring and managing complex IT systems to free up their critical resources by automating low and high-value tasks.",
       description3:"In recent years, the retail industry has been struggling to keep pace with the increasing demands of customers, growing competition, and the need for seamless supply chain operations. This is where AIOps comes in—an innovative technology that is transforming the way the retail industry operates. In this article, we'll explore what AIOps is and how it plays a crucial role in solving retail industry challenges."
    },
    {
        id:"heading2",
        "title": "Understanding AIOps",
        "description": "As the retail industry continues to grow, the need for efficient and effective IT operations becomes increasingly important. One technology that has emerged to meet this need is AIOps, Artificial Intelligence for IT operations.",
       orderedlist:[
        {
            "sidehead": "Definition of AIOps",
            "content": "AIOps is a technology that combines big data, machine learning, and artificial intelligence to streamline and automate IT operations. By leveraging these technologies, AIOps provides retailers with real-time visibility into their IT infrastructure, helping them to analyze massive amounts of data and detect anomalies before they become issues. With AIOps, retailers can gain valuable insights into their IT operations, allowing them to optimize their systems and processes for maximum efficiency and effectiveness."
          },
          {
            "sidehead": "Key components of AIOps",
            "content": "The three key components of AIOps are big data, machine learning, and artificial intelligence. At the core of AIOps is big data—a large volume of data generated by the retail industry's IT applications, servers, and network devices.",
            "content1": "Machine learning algorithms are used to analyze this data and generate insights that can help retailers proactively identify and resolve issues. By learning from past incidents, AIOps can identify patterns and predict potential issues before they occur.",
            "content2": "Finally, artificial intelligence is used to automate IT processes and reduce manual intervention. This allows IT teams to focus on more complex tasks, while AIOps handles routine tasks such as identifying the root cause of an issue."
          },
          {
            "sidehead": "How AIOps works",
            "content": "AIOps works by leveraging machine learning algorithms to analyze and learn from data generated by IT operations tools. By analyzing this data, AIOps can identify patterns and anomalies that may indicate a potential issue. Once an issue is identified, AIOps can automatically take action to resolve the issue or alert IT teams to take action. This can include tasks such as restarting a server, reallocating resources, or triggering an alert for IT teams.",
            "content1": "By automating these tasks, AIOps can help retailers reduce downtime, improve system performance, and optimize their IT operations for maximum efficiency and effectiveness.",
            "content2": "In conclusion, AIOps is a powerful technology that can help retailers streamline and automate their IT operations. By leveraging big data, machine learning, and artificial intelligence, AIOps can provide real-time visibility into IT infrastructure and help retailers proactively identify and resolve issues before they become problems."
          }       
            
       ]
    },
    {
        id:"heading3",
            "title": "The role of AIOps in the retail industry",
            "description": "The retail industry is constantly evolving, with retailers looking for new ways to improve customer experience, optimize inventory management, streamline supply chain operations, and improve workforce management. One technology that has emerged as a game-changer in the retail industry is Artificial Intelligence for IT Operations (AIOps).",   
          orderedlist:[
            {
                "sidehead": "Enhancing the customer experience",
                "content": "One of the key benefits of AIOps in the retail industry is the ability to enhance the customer experience. With AIOps, retailers can gain real-time insight into their IT infrastructure and quickly identify issues that could negatively impact the customer experience. For example, AIOps can help retailers detect anomalies in their online shopping platforms and proactively resolve them, ensuring that customers have a seamless shopping experience.",
                "content1": "Moreover, AIOps can help retailers personalize customer experiences by analyzing customer data and providing insights into customer behavior. Retailers can use this data to offer personalized recommendations, promotions, and discounts, ultimately increasing customer loyalty and satisfaction."
              },
              {
                "sidehead": "Optimizing inventory management",
                "content": "Another area where AIOps can help retailers is inventory management. AIOps can provide real-time inventory data, demand forecasting, and insights into supply chain issues. Retailers can use this data to ensure they have the right products in stock at the right time, reducing overstocking and understocking issues and improving profitability.",
                "content1": "Moreover, AIOps can help retailers optimize their pricing strategy by analyzing market trends, competitor pricing, and customer behavior. Retailers can use this data to adjust their pricing strategy in real time, ensuring that they remain competitive and profitable."
              },
              {
                "sidehead": "Streamlining supply chain operations",
                "content": "AIOps can also help retailers streamline supply chain operations by providing real-time visibility into the supply chain. With this data, retailers can identify potential supply chain issues and proactively address them, ensuring they can meet customer demands and minimize disruptions.",
                "content1": "Moreover, AIOps can help retailers optimize their logistics operations by analyzing delivery routes, transportation costs, and delivery times. Retailers can use this data to optimize their logistics operations, reducing costs and improving delivery times."
              },
              {
                "sidehead": "Improving workforce management",
                "content": "Finally, AIOps can help retailers improve workforce management by providing real-time data on employee productivity, store operations, and customer behavior. Retailers can use this data to optimize staff scheduling, reduce wait times, and offer personalized customer experiences, ultimately increasing customer satisfaction.",
                "content1": "Moreover, AIOps can help retailers identify potential employee issues, such as low productivity or high turnover rates, and proactively address them. Retailers can use this data to improve employee satisfaction, reduce turnover rates, and ultimately improve business performance.",
                "content2": "Overall, AIOps has the potential to revolutionize the retail industry by providing real-time insights into key business operations and enabling retailers to make data-driven decisions that improve the customer experience, optimize inventory management, streamline supply chain operations, and improve workforce management."
              }    
              
          ]
    },
      
      
      {
        id:"heading4",
            "title": "AIOps Use Cases in Retail",
            "description": "Retail is an ever-evolving industry that relies heavily on technology to stay ahead of the curve. With the advent of Artificial Intelligence for IT Operations (AIOps), retailers can now leverage the power of data to improve their operations and provide better customer experiences. This article explores some of the most popular use cases of AIOps in retail.",
        orderedlist:[
            {
                "sidehead": "Predictive Maintenance for Retail Equipment",
                "content": "One of the most significant challenges that retailers face is equipment failure. When refrigerators or HVAC systems break down, it can lead to significant downtime and lost revenue. AIOps can be used to monitor and analyze data from retail equipment, such as refrigerators and HVAC systems. By detecting anomalies in this data, AIOps can predict potential equipment failures, allowing retailers to proactively schedule maintenance and reduce downtime. This means that retailers can avoid costly repairs and lost revenue, while also ensuring that their customers receive the best possible experience.",
                "content1": "For example, a retailer that uses AIOps to monitor their refrigeration systems can detect when a compressor is starting to fail. The AIOps system can then alert the maintenance team, which can schedule a repair before the compressor fails. This ensures that the retailer's products are always kept at the correct temperature, and that customers can always find what they need."
              },
              {
                "sidehead": "Real-time Pricing and Promotions",
                "content": "AIOps can also be used to help retailers adjust pricing in real time based on customer demand and competition. Retailers can use this data to offer personalized promotions and pricing, leading to increased customer satisfaction and loyalty. By analyzing data from various sources, such as social media, customer reviews, and competitor pricing, AIOps can help retailers make informed decisions about their pricing strategy.",
                "content1": "For example, a retailer that uses AIOps to monitor social media can detect when customers are talking about a particular product. The AIOps system can then alert the pricing team, who can adjust the price of that product to match customer demand. This ensures that the retailer is always offering the best possible price to their customers, leading to increased customer satisfaction and loyalty."
              },
              {
                "sidehead": "Fraud Detection and Prevention",
                "content": "Fraud is a significant problem for retailers, and it can have a significant impact on their bottom line and reputation. AIOps can help retailers detect and prevent fraudulent activity by analyzing customer data and identifying unusual patterns. With this data, retailers can stop fraudulent activity before it impacts their bottom line and reputation.",
                "content1": "For example, a retailer that uses AIOps to monitor customer transactions can detect when a customer's behavior is unusual. The AIOps system can then alert the fraud prevention team, who can investigate the transaction and take appropriate action. This ensures that the retailer is always protecting their customers and their business from fraudulent activity."
              },
              {
                "sidehead": "Personalized Marketing and Recommendations",
                "content": "Personalized marketing and product recommendations are essential for retailers who want to provide the best possible customer experience. AIOps can be used to analyze customer behavior and identify patterns, allowing retailers to offer personalized marketing and product recommendations. This leads to higher customer engagement and loyalty, leading to increased sales and profitability for retailers.",
                "content1": "For example, a retailer that uses AIOps to monitor customer behavior can detect when a customer is interested in a particular product. The AIOps system can then recommend similar products to the customer, increasing the likelihood that they will make a purchase. This ensures that the retailer is always providing the best possible experience to their customers, leading to increased sales and profitability.",
                "content2": "In conclusion, AIOps is a powerful tool that can help retailers improve their operations and provide better customer experiences. By leveraging the power of data, retailers can proactively schedule maintenance, adjust pricing in real-time, detect and prevent fraudulent activity, and offer personalized marketing and product recommendations. With AIOps, retailers can stay ahead of the curve and provide the best possible experience for their customers."
              }                  

        ]    
              
      },
      {
        id:"heading5",
        "title": "Challenges Faced by the Retail Industry",
        "description": "The retail industry is a dynamic and ever-changing landscape that is constantly evolving to meet the needs and expectations of its customers. While this presents many opportunities for growth and innovation, it also poses many challenges that retailers must contend with to remain competitive and successful in the marketplace.",
    
            "orderedlist": [
              {
                "sidehead": "Increasing customer expectations",
                "content": "One of the biggest challenges facing retailers today is the increasing expectations of customers. In today's digital age, customers expect retailers to offer a seamless shopping experience across all touchpoints, whether online or in-person. This means that retailers must invest in technologies that enable them to provide personalized and relevant experiences to their customers while also ensuring that the customer journey is smooth and hassle-free.",
                "content1": "Moreover, customers expect retailers to be available 24/7, which means that retailers must have a strong and reliable online presence that is accessible from any device. Retailers who fail to meet these expectations risk losing customers and market share to competitors."
              },
              {
                "sidehead": "Growing competition and market saturation",
                "content": "Another major challenge facing the retail industry is growing competition and market saturation. The retail industry is saturated, with new entrants constantly disrupting the market. This means that retailers must constantly innovate to stay ahead of the competition and retain their customers.",
                "content1": "Moreover, retailers must also contend with the rise of e-commerce giants like Amazon, which have disrupted the traditional retail model and changed the way that customers shop. To remain competitive, retailers must embrace new technologies and business models that enable them to offer unique and differentiated experiences to their customers."
              },
              {
                "sidehead": "Adapting to new technologies and trends",
                "content": "The retail industry is constantly evolving, with new technologies and trends emerging all the time. Retailers must adapt to these changes to remain competitive and meet customer expectations. For example, the rise of mobile and social media has changed the way that customers interact with retailers, and retailers must be able to leverage these channels effectively to reach their target audience.",
                "content1": "Moreover, retailers must also embrace emerging technologies like artificial intelligence and machine learning, which can help them personalize the customer experience and make more informed business decisions."
              },
              {
                "sidehead": "Maintaining data privacy and security",
                "content": "Retailers deal with massive amounts of customer data, making data privacy and security a top priority. Retailers must invest in robust data security measures to protect customer information and maintain their reputation. This means implementing strong encryption protocols, firewalls, and other security measures to prevent data breaches and unauthorized access.",
                "content1": "Moreover, retailers must also comply with data privacy regulations like GDPR and CCPA, which impose strict requirements on how customer data is collected, stored, and used. Failure to comply with these regulations can result in hefty fines and damage to the retailer's reputation.",
            "content2": "In conclusion, the retail industry faces many challenges, but by embracing new technologies, innovating, and prioritizing data privacy and security, retailers can overcome these challenges and thrive in the marketplace."
                
            }
            ],
          
          
    },
    { 
        id:"heading6",
        "title": "Conclusion",
        "description": "In conclusion, AIOps is an innovative technology that is transforming the retail industry by providing real-time visibility, data analysis, and automation capabilities. AIOps can help retailers streamline their operations and retail merchandising, improve the customer experience, and reduce costs. However, retailers need to ensure that they address the challenges they face and invest in robust data security measures to fully realize the benefits of AIOps technology.",
        "description5":"Leading retailers are experiencing the biggest challenge in choosing the right AI/ML advisor toward digital transformation.",
        description6:"We can help you overcome the problem by offering you a personalized and no-obligation consultation.",
        description7:"If this is your highest priority, please feel free to schedule a call with us!",
       }
 
      
];




const AIOPSretail = () => {
    const [show, setShow] = useState(false);
    const handleShow = () => setShow(true);
    const handleClose = () => setShow(false);
    const history = useNavigate();
    const btnColor = {
        backgroundColor: "#ecac27",
        borderRadius: "50px",
        cursor: "pointer",
    };

    const navigateTowebinarspage = (id) => {
        history(`/blogs/${id}`);
    };

    const [selectedId, setId] = useState("");
    const hightlightText = (id) => {
        setId(id);
    };

    const UnhightlightText = () => {
        setId("");
    };

    const {
        register,
        handleSubmit,
        formState: { errors },
        reset,
    } = useForm({
        resolver: yupResolver(schema),
    });

    const submit = (data) => {
        return emailjs
            .sendForm(
                "service_e7ig9fn",
                "template_g62rj9d",
                formDetails.current,
                "yz7dQlM6o3Rz3cnB8"
            )
            .then(
                console.log("mail sent"),
                localStorage.setItem("cookie", 4),
                reset(),
                handleShow(),
                (error) => {
                    console.log(error.text);
                }
            );
    };

    const formDetails = useRef();
    const [activeHeading, setActiveHeading] = useState(null);
    const descriptionsRef = useRef([]);

    const scrollToSection = (id) => {
        const section = document.getElementById(id);
        if (section) {
            section.scrollIntoView({ behavior: 'smooth' });
        }
    };

    const handleScroll = () => {
        const sections = descriptionsRef.current;
        sections.forEach((section) => {
            const rect = section.getBoundingClientRect();
            if (rect.top >= 0 && rect.top < window.innerHeight) {
                setActiveHeading(section.id);
            }
        });
    };

    useEffect(() => {
        window.addEventListener('scroll', handleScroll);
        return () => {
            window.removeEventListener('scroll', handleScroll);
        };
    }, []);


    return (
        <>
        <Helmet>
        <meta charSet="utf-8" />
        <title>How is AIOps Revolutionizing the Retail Industry | Amnet Digital</title>
        <meta name="description" content="Dive into our blog post for valuable insights on the game-changing impact of AIOps in revolutionizing the way retailers operate 
         and engage with customers." />
        <meta name="keywords" content="" />
      </Helmet>
        <div className="scroll-class">
            <div class="background-container">
                <div class="centered-text">
                    <h1>November 19, 2024</h1>
                    <p>Perplexity: AI search diruptor is taking a big swing with new shopping feature</p>
                </div>
            </div>

            <div className='scrolling-bar'>
                <div className='row space-above w-93 mx-auto'>
                    <div className="col-lg-3 col-md-12 col-sm-12 col-12 sticky-cls-first">
                        {headings
                            .filter((heading) => heading.title)
                            .map((heading) => (
                                <div
                                    key={heading.id}
                                    className={`heading ${activeHeading === heading.id ? "active" : ""}`}
                                    onClick={() => scrollToSection(heading.id)}
                                >
                                    {heading.title}
                                </div>
                            ))}
                        <button className='schedule-button'>Schedule a call</button>
                    </div>

                    <div className="col-lg-6 col-sm-12 col-md-12 col-12 descriptions-column">
                        <h1 className="reading-text">Reading time:</h1>
                        <div className="spacing-divs-xss"></div>
                        <div className="fs-12 fw-bold minute-text">
                            <img src={clock} className="me-2" />
                            4 minutes
                        </div>
                        {headings.map((heading, index) => (
                            <div
                                key={heading.id}
                                id={heading.id}
                                ref={(el) => (descriptionsRef.current[index] = el)}
                                className="description-section"
                            >
                                <div className="spacing-divs-l"></div>
                                {heading.title && <h1>{heading.title}</h1>}
                                {heading.description && <p>{heading.description}</p>}
                                {heading.description1 && <p>{heading.description1}</p>}
                                {heading.heading1 && <h2>{heading.heading1}</h2>}
                           
                                {heading.description2 && <p>{heading.description2}</p>}
                                {heading.description3 && <p>{heading.description3}</p>}
                               
                               
                                {heading.heading2 && <h3>{heading.heading2}</h3>}
                                {heading.heading3 && <h2>{heading.heading3}</h2>}
                                {heading.question && (
                                    <h5>
                                        <span className="question-style">{heading.question}</span>
                                        {heading.details && <span className="fs-14 fw-300">{heading.details}</span>}
                                    </h5>
                                )}
                                {heading.image && (
                                                    <img src={heading.image}  className='w-100'/>
                                                    
                                                )}
                                {heading.orderedlist && heading.orderedlist.length > 0 && (
                                    <ol className="pl-4">
                                        {heading.orderedlist.map((response, responseIndex) => (
                                            <li key={response.sidehead} className="fs-14 pb-3 ">
                                                <span className="fs-14 fw-bold" >{response.sidehead}</span>
                                                {response.content && <p className="mt-3">{response.content}</p>}
                                               
                                                {response.content1 && <p className="mt-3">{response.content1}</p>}
                                                {response.content2 && <p className="mt-3">{response.content2}</p>}
                                                {response.content3 && <p className="mt-3">{response.content3}</p>}
                                                {response.content4 && <p className="mt-3">{response.content4}</p>}
                                                {response.image && (
                                                    <img src={response.image}  className='w-100'/>
                                                    
                                                )}
                                            </li>
                                        ))}
                                    </ol>
                                )}
                                 {heading.description5 && <p className='fw-bold'>{heading.description5}</p>}
                                 {heading.description6 && <p className='fw-bold'>{heading.description6}</p>}
                                 {heading.description7 && <p className='fw-bold'>{heading.description7}</p>}
                            </div>
                        ))}


                        <div className="spacing-divs-ss"></div>
                        <div className='hr-line-category'></div>
                        <p className='category-font'>Category: <span className='ai-styles'>AI Industry News</span></p>
                        <div className='hr-line-category'></div>
                        <div className="share-container d-flex flex-row justify-content-between">
                            <div className='share-text'>Share this article:</div>
                            <div className="social-icons">
                                <span className="icon linkedin">
                                    <a href="https://www.linkedin.com" target='_blank'> <img src={linkedin} /></a>
                                </span>
                                <span className="icon linkedin">
                                    <a href="https://www.twitter.com" target='_blank'>  <img src={twitter} /></a>
                                </span>
                                <span className="icon linkedin">
                                    <a href="https://www.facebook.com" target='_blank'>  <img src={facebook} /></a>
                                </span>
                                <span className="linkedin">
                                    <a href="https://www.instagram.com" target='_blank'>  <img src={instagram} /></a>
                                </span>
                            </div>
                        </div>
                    </div>

                    <div className="col-lg-3 col-md-12 col-sm-12 col-12 sticky-cls mt-4">
                        <div className="card servicess">
                            <a href="https://addepto.com/contextclue-ai-text-analysis-tool-by-addepto/">
                                <div className="animation__img">
                                    <img src="https://addepto.com/wp-content/uploads/2023/06/contextclue-featured-image.webp" alt="" data-scroll-zoom />
                                </div>
                                <div className="card__content">
                                    <h5 className="h5">ContextClue: AI Text Analysis Tool by Addepto</h5>

                                    <div className="flex justify-content-end">
                                        <span className="h6 primary pt-3">check this service</span>
                                    </div>
                                </div>
                            </a>
                        </div>
                        <div class="flex fd-c ai-fs card newsletter">
                            <h2 class="h5">Sign Up for Newsletter</h2>
                            <form
                                ref={formDetails}
                                onSubmit={handleSubmit(submit)}
                                className="pt-4"
                            >
                                <div className='row'>
                                    <div className="col-xs-12 col-sm-12 col-12">
                                        <label className="font-form text-start ">
                                            Name<span className="green-star">*</span>
                                            <input
                                                className="w-100 spacing-input-l border-rounded"
                                                type="text"
                                                placeholder=' Name'
                                                name="fName"
                                                {...register("fName")}
                                            />
                                        </label>
                                        <p className="fs-13 text-danger fw-bold-400 text-start">
                                            {errors.fName?.message}
                                        </p>
                                    </div>
                                    <div className="col-xs-12 col-sm-12 col-12">
                                        <label className="font-form text-start">
                                            E-mail<span className="green-star">*</span>
                                        </label>
                                        <p className="email_field">
                                            <input
                                                className="w-100 spacing-input-l  border-rounded"
                                                placeholder='Email address'
                                                type="email"
                                                name="email"
                                                {...register("email")}
                                            />
                                        </p>
                                        <p className="fs-13 text-danger fw-bold-400 text-start">
                                            {errors.email?.message}
                                        </p>
                                    </div>
                                </div>
                                <div className="w-100 d-flex checkbox-space">
                                    <div className="w-6">
                                        <input
                                            className='checkmarks-in'
                                            type="checkbox"
                                            name="acceptCheckbox"
                                            {...register("acceptCheckbox")}
                                        ></input>
                                    </div>
                                    <div className="w-94 pl-2">
                                        <div className="pt-1 fs-12 ps-2">
                                            * I want to receive newsletter
                                        </div>
                                        <br />
                                    </div>
                                </div>
                                <p className="fs-13 text-danger fw-bold-400">
                                    {errors.acceptCheckbox?.message}
                                </p>
                                <p className='fs-12'>See our <span className='fw-bold fs-12'>Pivacy Policy</span></p>
                                <p className='signup-button'>Sign up</p>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <div className='grey-background'>
                <div className="row w-93 mx-auto new-case-studies-row ">
                    <div className="d-flex justify-content-between align-items-center  mb-3">
                        <div className="text-start related-articles">Related Articles</div>
                        <div className="text-end check-articles">check all Articles</div>
                    </div>
                    {Insightdata.perplexitydetails.map((list) => {
                        return (
                            <div
                                className="col-lg-3 col-md-6 col-sm-12 col-xs-12 cr-pointer highlight-text d-flex align-items-strech mb-4"
                                key={list.id}
                                onClick={() => {
                                    navigateTowebinarspage(list.id);
                                }}
                                onMouseEnter={() => {
                                    hightlightText(list.id);
                                }}
                                onMouseLeave={() => {
                                    UnhightlightText();
                                }}
                            >
                                <div className="border-0  card animation-card-image mr-4 ">
                                    <a
                                        className="anchor_styles achorhover"
                                        href={`/blogs/${list.id}`}
                                    >
                                        <div className="card-header border-0 bgc-white p-0 position-relative">
                                            <img
                                                src={list.image}
                                                alt={list.title}
                                                className="blog_images"
                                            />
                                            <button className="btn btn-white position-absolute bottom-right-button">
                                                AI Industry News
                                            </button>
                                        </div>
                                        <div className="card-body propensity-modelling height-auto margin pb-2">
                                            <h1 className="color-date">{list.date}</h1>
                                            <h1 className="card-body-heading pb-0 pt-0">
                                                {list.title}
                                            </h1>
                                            <p className="card_body_description">
                                                {list.description}
                                            </p>
                                        </div>
                                   
                                    </a>
                                </div>
                            </div>
                        );
                    })}
                </div>
            </div>
        </div>
        </>
    );
};

export default AIOPSretail;